name: Terraform Datalake via OIDC

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

permissions:
  id-token: write     # Required for AWS OIDC
  contents: read      # Required to checkout repository

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with: 
          role-to-assume: arn:aws:iam::483416847573:role/firstroleinoidc
          aws-region: eu-west-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # Debugging â€“ Lists directory structure
      - name: List files (root)
        run: ls -la

      - name: List files (environments)
        run: ls -la ./environments

      # Terraform commands in the environments directory
      - name: Terraform Init
        working-directory: ./environments
        run: terraform init

      - name: Terraform Validate
        working-directory: ./environments
        run: terraform validate

      - name: Terraform Plan
        working-directory: ./environments
        run: terraform plan -input=false

      - name: Terraform Apply 
        if: github.ref == 'refs/heads/main'
        working-directory: ./environments
        run: terraform apply -auto-approve -input=false
